-- clean application stuff
DROP TABLE IF EXISTS Auteur;
DROP TABLE IF EXISTS Collec;
DROP TABLE IF EXISTS Nationalite;
DROP TABLE IF EXISTS Theme;
DROP TABLE IF EXISTS Utilisateur;
DROP TABLE IF EXISTS Liste;
DROP TABLE IF EXISTS Livre;
DROP TABLE IF EXISTS A_ecrit;
DROP TABLE IF EXISTS Livre_a_Theme;
DROP TABLE IF EXISTS Auteur_vient_de;
DROP TABLE IF EXISTS A_lu;
DROP TABLE IF EXISTS Aime;
DROP TABLE IF EXISTS User_vient_de;
DROP TABLE IF EXISTS Est_dans;
DROP TABLE IF EXISTS Autorisation;